@FilmDetailsTask @db

Feature: Film Details as Task 2 automation feature

  Scenario: Get a list of all films created by join
    Given the filmdetails service is up and running
    When I request a list of all filmDetails
    Then I should receive a list of filmDetails covers given data
      | "Academy Dinosaur"            | "A Epic Drama of a Feminist And a Mad Scientist who must Battle a Teacher in The Canadian Rockies"                                   | 2006 | "Documentary" | "Rock Dukakis, Mary Keitel, Johnny Cage, Penelope Guiness, Sandra Peck, Christian Gable, Oprah Kilmer, Warren Nolte, Lucille Tracy, Mena Temple"                                                     |
      | "Ace Goldfinger"              | "A Astounding Epistle of a Database Administrator And a Explorer who must Find a Car in Ancient China"                               | 2006 | "Horror"      | "Minnie Zellweger, Chris Depp, Bob Fawcett, Sean Guiness"                                                                                                                                            |
      | "Adaptation Holes"            | "A Astounding Reflection of a Lumberjack And a Car who must Sink a Lumberjack in A Baloon Factory"                                   | 2006 | "Documentary" | "Cameron Streep, Bob Fawcett, Nick Wahlberg, Ray Johansson, Julianne Dench"                                                                                                                          |
      | "Affair Prejudice"            | "A Fanciful Documentary of a Frisbee And a Lumberjack who must Chase a Monkey in A Shark Tank"                                       | 2006 | "Horror"      | "Jodie Degeneres, Kenneth Pesci, Fay Winslet, Oprah Kilmer, Scarlett Damon"                                                                                                                          |
      | "African Egg"                 | "A Fast-Paced Documentary of a Pastry Chef And a Dentist who must Pursue a Forensic Psychologist in The Gulf of Mexico"              | 2006 | "Family"      | "Dustin Tautou, Matthew Leigh, Gary Phoenix, Matthew Carrey, Thora Temple"                                                                                                                           |
      | "Agent Truman"                | "A Intrepid Panorama of a Robot And a Boy who must Escape a Sumo Wrestler in Ancient China"                                          | 2006 | "Foreign"     | "Warren Nolte, Sandra Kilmer, Jayne Neeson, Morgan Williams, Kirsten Paltrow, Kenneth Hoffman, Reese West"                                                                                           |
      | "Airplane Sierra"             | "A Touching Saga of a Hunter And a Butler who must Discover a Butler in A Jet Boat"                                                  | 2006 | "Comedy"      | "Mena Hopper, Jim Mostel, Michael Bolger, Oprah Kilmer, Richard Penn"                                                                                                                                |
      | "Airport Pollock"             | "A Epic Tale of a Moose And a Girl who must Confront a Monkey in Ancient India"                                                      | 2006 | "Horror"      | "Lucille Dee, Susan Davis, Fay Kilmer, Gene Willis"                                                                                                                                                  |
      | "Alabama Devil"               | "A Thoughtful Panorama of a Database Administrator And a Mad Scientist who must Outgun a Mad Scientist in A Jet Boat"                | 2006 | "Horror"      | "William Hackman, Rip Crawford, Rip Winslet, Greta Keitel, Christian Gable, Mena Temple, Meryl Allen, Warren Nolte, Elvis Marx"                                                                      |
      | "Aladdin Calendar"            | "A Action-Packed Tale of a Man And a Lumberjack who must Reach a Feminist in Ancient China"                                          | 2006 | "Sports"      | "Greta Malden, Rock Dukakis, Ray Johansson, Renee Tracy, Val Bolger, Judy Dean, Jada Ryder, Alec Wayne"                                                                                              |
      | "Alamo Videotape"             | "A Boring Epistle of a Butler And a Cat who must Fight a Pastry Chef in A MySQL Convention"                                          | 2006 | "Foreign"     | "Michael Bening, Johnny Cage, Scarlett Damon, Sean Guiness"                                                                                                                                          |
      | "Alaska Phantom"              | "A Fanciful Saga of a Hunter And a Pastry Chef who must Vanquish a Boy in Australia"                                                 | 2006 | "Music"       | "Val Bolger, Burt Posey, Gene Mckellen, Jeff Silverstone, Sylvester Dern, Albert Johansson, Sidney Crowe"                                                                                            |
      | "Ali Forever"                 | "A Action-Packed Drama of a Dentist And a Crocodile who must Battle a Feminist in The Canadian Rockies"                              | 2006 | "Horror"      | "Christopher Berry, Kenneth Torn, Cary Mcconaughey, Jon Chase, Morgan Mcdormand"                                                                                                                     |
      | "Alice Fantasia"              | "A Emotional Drama of a A Shark And a Database Administrator who must Vanquish a Pioneer in Soviet Georgia"                          | 2006 | "Classics"    | "Woody Hoffman, Rock Dukakis, Minnie Zellweger, Morgan Williams"                                                                                                                                     |
      | "Alien Center"                | "A Brilliant Drama of a Cat And a Mad Scientist who must Battle a Feminist in A MySQL Convention"                                    | 2006 | "Foreign"     | "Sidney Crowe, Kenneth Paltrow, Humphrey Willis, Renee Tracy, Burt Dukakis, Mena Hopper"                                                                                                             |
      | "Alley Evolution"             | "A Fast-Paced Drama of a Robot And a Composer who must Battle a Astronaut in New Orleans"                                            | 2006 | "Foreign"     | "Gregory Gooding, Jude Cruise, John Suvari, Karl Berry, Albert Johansson"                                                                                                                            |
      | "Alone Trip"                  | "A Fast-Paced Character Study of a Composer And a Dog who must Outgun a Boat in An Abandoned Fun House"                              | 2006 | "Music"       | "Renee Ball, Ed Chase, Spencer Depp, Karl Berry, Laurence Bullock, Woody Jolie, Chris Depp, Uma Wood"                                                                                                |
      | "Alter Victory"               | "A Thoughtful Drama of a Composer And a Feminist who must Meet a Secret Agent in The Canadian Rockies"                               | 2006 | "Animation"   | "Jada Ryder, Angela Witherspoon, Oprah Kilmer, Reese Kilmer"                                                                                                                                         |
      | "Amadeus Holy"                | "A Emotional Display of a Pioneer And a Technical Writer who must Battle a Man in A Baloon"                                          | 2006 | "Action"      | "Penelope Cronyn, Kirk Jovovich, Julia Mcqueen, Johnny Lollobrigida, Val Bolger, James Pitt"                                                                                                         |
      | "Amelie Hellfighters"         | "A Boring Drama of a Woman And a Squirrel who must Conquer a Student in A Baloon"                                                    | 2006 | "Music"       | "Laura Brody, Carmen Hunt, Ewan Gooding, Ian Tandy, Walter Torn, Ed Mansfield"                                                                                                                       |
      | "American Circus"             | "A Insightful Drama of a Girl And a Astronaut who must Face a Database Administrator in A Shark Tank"                                | 2006 | "Action"      | "Rip Crawford, Sidney Crowe, Kevin Bloom, Warren Jackman, Frances Tomei"                                                                                                                             |
      | "Amistad Midsummer"           | "A Emotional Character Study of a Dentist And a Crocodile who must Meet a Sumo Wrestler in California"                               | 2006 | "New"         | "Cary Mcconaughey, Daryl Wahlberg, Scarlett Bening, Salma Nolte"                                                                                                                                     |
      | "Anaconda Confessions"        | "A Lacklusture Display of a Dentist And a Dentist who must Fight a Girl in Australia"                                                | 2006 | "Animation"   | "Jennifer Davis, Humphrey Willis, Penelope Guiness, Jayne Nolte, Elvis Marx"                                                                                                                         |
      | "Analyze Hoosiers"            | "A Thoughtful Display of a Explorer And a Pastry Chef who must Overcome a Feminist in The Sahara Desert"                             | 2006 | "Horror"      | "Ed Guiness, Jessica Bailey, Tom Miranda, Greta Malden, Tom Mckellen"                                                                                                                                |
      | "Angels Life"                 | "A Thoughtful Display of a Woman And a Astronaut who must Battle a Robot in Berlin"                                                  | 2006 | "New"         | "Ed Mansfield, Renee Ball, Grace Mostel, Laurence Bullock, Nick Degeneres, Julia Barrymore, Penelope Guiness, Jennifer Davis, Christopher Berry"                                                     |
      | "Annie Identity"              | "A Amazing Panorama of a Pastry Chef And a Boat who must Escape a Woman in An Abandoned Amusement Park"                              | 2006 | "Sci-Fi"      | "Cate Mcqueen, Adam Grant, Greta Keitel"                                                                                                                                                             |
      | "Anonymous Human"             | "A Amazing Reflection of a Database Administrator And a Astronaut who must Outrace a Database Administrator in A Shark Tank"         | 2006 | "Sports"      | "Jim Mostel, Susan Davis, Grace Mostel, Emily Dee, Fay Kilmer, Mena Hopper, Whoopi Hurt, Meryl Gibson, Ed Guiness"                                                                                   |
      | "Anthem Luke"                 | "A Touching Panorama of a Waitress And a Woman who must Outrace a Dog in An Abandoned Amusement Park"                                | 2006 | "Comedy"      | "Milla Keitel, Oprah Kilmer"                                                                                                                                                                         |
      | "Antitrust Tomatoes"          | "A Fateful Yarn of a Womanizer And a Feminist who must Succumb a Database Administrator in Ancient India"                            | 2006 | "Action"      | "Uma Wood, Reese West, Sidney Crowe, Bette Nicholson, Salma Nolte, William Hackman, Renee Ball"                                                                                                      |
      | "Anything Savannah"           | "A Epic Story of a Pastry Chef And a Woman who must Chase a Feminist in An Abandoned Fun House"                                      | 2006 | "Horror"      | "Lisa Monroe, Christopher West, Joe Swank"                                                                                                                                                           |
      | "Apache Divine"               | "A Awe-Inspiring Reflection of a Pastry Chef And a Teacher who must Overcome a Sumo Wrestler in A U-Boat"                            | 2006 | "Family"      | "Anne Cronyn, Henry Berry, Nick Wahlberg, Cuba Olivier"                                                                                                                                              |
      | "Apocalypse Flamingos"        | "A Astounding Story of a Dog And a Squirrel who must Defeat a Woman in An Abandoned Amusement Park"                                  | 2006 | "New"         | "Oprah Kilmer, Vivien Basinger, Russell Close, Will Wilson, Mae Hoffman"                                                                                                                             |
      | "Apollo Teen"                 | "A Action-Packed Reflection of a Crocodile And a Explorer who must Find a Sumo Wrestler in An Abandoned Mine Shaft"                  | 2006 | "Drama"       | "Mae Hoffman, Woody Jolie, Albert Johansson, Oprah Kilmer, Mena Hopper, Jeff Silverstone, Debbie Akroyd, Ed Mansfield"                                                                               |
      | "Arabia Dogma"                | "A Touching Epistle of a Madman And a Mad Cow who must Defeat a Student in Nigeria"                                                  | 2006 | "Horror"      | "Julia Mcqueen, Rip Crawford, Burt Posey, Walter Torn, Russell Bacall, Lisa Monroe, Jude Cruise, Greta Malden, Sean Williams, Frances Tomei, Johnny Cage, Karl Berry"                                |
      | "Arachnophobia Rollercoaster" | "A Action-Packed Reflection of a Pastry Chef And a Composer who must Discover a Mad Scientist in The First Manned Space Station"     | 2006 | "Horror"      | "Rita Reynolds, Humphrey Garland, Grace Mostel, Morgan Hopkins, Ewan Gooding, Judy Dean, Daryl Wahlberg, Cuba Allen"                                                                                 |
      | "Argonauts Town"              | "A Emotional Epistle of a Forensic Psychologist And a Butler who must Challenge a Waitress in An Abandoned Mine Shaft"               | 2006 | "Animation"   | "Julia Barrymore, Kevin Garland, Gary Penn, Dan Streep, Gene Willis"                                                                                                                                 |
      | "Arizona Bang"                | "A Brilliant Panorama of a Mad Scientist And a Mad Cow who must Meet a Pioneer in A Monastery"                                       | 2006 | "Classics"    | "Karl Berry, Greta Keitel, Ray Johansson, Russell Bacall"                                                                                                                                            |
      | "Ark Ridgemont"               | "A Beautiful Yarn of a Pioneer And a Monkey who must Pursue a Explorer in The Sahara Desert"                                         | 2006 | "Action"      | "Nick Degeneres, Parker Goldberg, Audrey Bailey"                                                                                                                                                     |
      | "Armageddon Lost"             | "A Fast-Paced Tale of a Boat And a Teacher who must Succumb a Composer in An Abandoned Mine Shaft"                                   | 2006 | "Sci-Fi"      | "James Pitt, Penelope Cronyn, Kim Allen, Gregory Gooding, Gene Mckellen, Cuba Allen, Angela Hudson"                                                                                                  |
      | "Army Flintstones"            | "A Boring Saga of a Database Administrator And a Womanizer who must Battle a Waitress in Nigeria"                                    | 2006 | "Documentary" | "Penelope Cronyn, Matthew Carrey, Russell Close, Gene Willis, Ed Chase, Cary Mcconaughey, Mae Hoffman"                                                                                               |
      | "Arsenic Independence"        | "A Fanciful Documentary of a Mad Cow And a Womanizer who must Find a Dentist in Berlin"                                              | 2006 | "Travel"      | "Rita Reynolds, Cuba Allen, Oprah Kilmer"                                                                                                                                                            |
      | "Artist Coldblooded"          | "A Stunning Reflection of a Robot And a Moose who must Challenge a Woman in California"                                              | 2006 | "Sports"      | "Sidney Crowe, Sandra Kilmer, Jayne Neeson, Meryl Allen, Renee Tracy, Kirk Jovovich, Ed Chase"                                                                                                       |
      | "Atlantis Cause"              | "A Thrilling Yarn of a Feminist And a Hunter who must Fight a Technical Writer in A Shark Tank"                                      | 2006 | "Family"      | "Frances Tomei, Cuba Birch, Chris Depp, Woody Hoffman, Julianne Dench, Harvey Hope, Cate Harris, Audrey Olivier, Greta Keitel"                                                                       |
      | "Attacks Hate"                | "A Fast-Paced Panorama of a Technical Writer And a Mad Scientist who must Find a Feminist in An Abandoned Mine Shaft"                | 2006 | "Sci-Fi"      | "Dan Torn, Burt Temple, Milla Keitel, Groucho Dunst"                                                                                                                                                 |
      | "Attraction Newton"           | "A Astounding Panorama of a Composer And a Frisbee who must Reach a Husband in Ancient Japan"                                        | 2006 | "New"         | "Uma Wood, Rip Winslet, Gary Penn, Christopher West"                                                                                                                                                 |
      | "Autumn Crow"                 | "A Beautiful Tale of a Dentist And a Mad Cow who must Battle a Moose in The Sahara Desert"                                           | 2006 | "Games"       | "Angela Hudson, James Pitt, Dustin Tautou"                                                                                                                                                           |
      | "Baby Hall"                   | "A Boring Character Study of a A Shark And a Girl who must Outrace a Feminist in An Abandoned Mine Shaft"                            | 2006 | "Foreign"     | "Matthew Johansson, River Dean, Charlize Dench, Kevin Garland, Nick Wahlberg, Daryl Wahlberg, Minnie Kilmer, Vivien Basinger"                                                                        |
      | "Backlash Undefeated"         | "A Stunning Character Study of a Mad Scientist And a Mad Cow who must Kill a Car in A Monastery"                                     | 2006 | "Children"    | "Jane Jackman, Kevin Garland, Spencer Peck, Christopher Berry, Christian Akroyd, Sylvester Dern, Dan Streep"                                                                                         |
      | "Badman Dawn"                 | "A Emotional Panorama of a Pioneer And a Composer who must Escape a Mad Scientist in A Jet Boat"                                     | 2006 | "Sci-Fi"      | "Ben Willis, Thora Temple, Alan Dreyfuss, Greta Keitel, Olympia Pfeiffer, Warren Jackman, Harrison Bale, Cuba Allen"                                                                                 |
      | "Baked Cleopatra"             | "A Stunning Drama of a Forensic Psychologist And a Husband who must Overcome a Waitress in A Monastery"                              | 2006 | "Family"      | "Michelle Mcconaughey"                                                                                                                                                                               |
      | "Balloon Homeward"            | "A Insightful Panorama of a Forensic Psychologist And a Mad Cow who must Build a Mad Scientist in The First Manned Space Station"    | 2006 | "Music"       | "Parker Goldberg, Rock Dukakis, Gary Penn, Mena Temple, Richard Penn, Renee Ball"                                                                                                                    |
      | "Ballroom Mockingbird"        | "A Thrilling Documentary of a Composer And a Monkey who must Find a Feminist in California"                                          | 2006 | "Foreign"     | "Ben Willis, Gene Mckellen, Daryl Wahlberg, Adam Grant, Judy Dean, Harrison Bale, Lucille Dee"                                                                                                       |
      | "Bang Kwai"                   | "A Epic Drama of a Madman And a Cat who must Face a A Shark in An Abandoned Amusement Park"                                          | 2006 | "Family"      | "Julia Barrymore, Bette Nicholson, Walter Torn, Fay Wood, Russell Temple, Sandra Peck, Michelle Mcconaughey"                                                                                         |
      | "Banger Pinocchio"            | "A Awe-Inspiring Drama of a Car And a Pastry Chef who must Chase a Crocodile in The First Manned Space Station"                      | 2006 | "Music"       | "Gene Willis, Johnny Lollobrigida, Audrey Bailey, Lucille Tracy, Dustin Tautou, Jayne Neeson"                                                                                                        |
      | "Barbarella Streetcar"        | "A Awe-Inspiring Story of a Feminist And a Cat who must Conquer a Dog in A Monastery"                                                | 2006 | "Sci-Fi"      | "Gene Mckellen, Cuba Allen, Alan Dreyfuss, Nick Degeneres, Mary Tandy"                                                                                                                               |
      | "Barefoot Manchurian"         | "A Intrepid Story of a Cat And a Student who must Vanquish a Girl in An Abandoned Amusement Park"                                    | 2006 | "Action"      | "Will Wilson, Ed Mansfield, Elvis Marx, Milla Peck, Jennifer Davis, Daryl Crawford, Kirk Jovovich, Morgan Williams"                                                                                  |
      | "Basic Easy"                  | "A Stunning Epistle of a Man And a Husband who must Reach a Mad Scientist in A Jet Boat"                                             | 2006 | "Travel"      | "Jessica Bailey, Emily Dee, Ewan Gooding, Penelope Monroe, Groucho Williams, Greta Keitel"                                                                                                           |
      | "Beach Heartbreakers"         | "A Fateful Display of a Womanizer And a Mad Scientist who must Outgun a A Shark in Soviet Georgia"                                   | 2006 | "Documentary" | "Woody Hoffman, Ben Willis, Gene Willis, Nick Stallone, Mena Temple, Frances Tomei, Harvey Hope"                                                                                                     |
      | "Bear Graceland"              | "A Astounding Saga of a Dog And a Boy who must Kill a Teacher in The First Manned Space Station"                                     | 2006 | "Children"    | "Penelope Cronyn, Ben Harris, Scarlett Damon"                                                                                                                                                        |
      | "Beast Hunchback"             | "A Awe-Inspiring Epistle of a Student And a Squirrel who must Defeat a Boy in Ancient China"                                         | 2006 | "Classics"    | "Kenneth Torn, Jodie Degeneres, Bette Nicholson, Angelina Astaire, Susan Davis"                                                                                                                      |
      | "Beauty Grease"               | "A Fast-Paced Display of a Composer And a Moose who must Sink a Robot in An Abandoned Mine Shaft"                                    | 2006 | "Drama"       | "Lucille Dee, Nick Degeneres, Ed Mansfield, Michael Bening, Cameron Zellweger"                                                                                                                       |
      | "Bed Highball"                | "A Astounding Panorama of a Lumberjack And a Dog who must Redeem a Woman in An Abandoned Fun House"                                  | 2006 | "Documentary" | "Gina Degeneres, Susan Davis, Albert Nolte, Audrey Bailey, Jennifer Davis"                                                                                                                           |
      | "Bedazzled Married"           | "A Astounding Character Study of a Madman And a Robot who must Meet a Mad Scientist in An Abandoned Fun House"                       | 2006 | "Family"      | "Gary Phoenix, Laurence Bullock, Reese West, Dan Harris, Lucille Tracy, Jayne Nolte, Penelope Monroe"                                                                                                |
      | "Beethoven Exorcist"          | "A Epic Display of a Pioneer And a Student who must Challenge a Butler in The Gulf of Mexico"                                        | 2006 | "Drama"       | "Scarlett Bening, Sandra Peck, Bela Walken, Warren Jackman, Vivien Basinger, Minnie Kilmer"                                                                                                          |
      | "Behavior Runaway"            | "A Unbelieveable Drama of a Student And a Husband who must Outrace a Sumo Wrestler in Berlin"                                        | 2006 | "Horror"      | "Rita Reynolds, Reese Kilmer, Daryl Wahlberg, Tim Hackman, Ed Guiness"                                                                                                                               |
      | "Beneath Rush"                | "A Astounding Panorama of a Man And a Monkey who must Discover a Man in The First Manned Space Station"                              | 2006 | "Children"    | "Angelina Astaire, Gene Willis, Vivien Basinger, Reese Kilmer, Susan Davis, Jane Jackman, Chris Bridges"                                                                                             |
      | "Berets Agent"                | "A Taut Saga of a Crocodile And a Boy who must Overcome a Technical Writer in Ancient China"                                         | 2006 | "Action"      | "Julia Fawcett, Cate Harris, Meryl Allen, Julia Barrymore, Grace Mostel, Julianne Dench, Jessica Bailey, William Hackman, Ian Tandy, Angela Witherspoon"                                             |
      | "Betrayed Rear"               | "A Emotional Character Study of a Boat And a Pioneer who must Find a Explorer in A Shark Tank"                                       | 2006 | "Children"    | "Christian Akroyd, Morgan Mcdormand, Nick Degeneres, Angelina Astaire"                                                                                                                               |
      | "Beverly Outlaw"              | "A Fanciful Documentary of a Womanizer And a Boat who must Defeat a Madman in The First Manned Space Station"                        | 2006 | "Sci-Fi"      | "Ralph Cruz, Jodie Degeneres, Sandra Peck, John Suvari"                                                                                                                                              |
      | "Bikini Borrowers"            | "A Astounding Drama of a Astronaut And a Cat who must Discover a Woman in The First Manned Space Station"                            | 2006 | "Animation"   | "Penelope Cronyn, Bette Nicholson"                                                                                                                                                                   |
      | "Bilko Anonymous"             | "A Emotional Reflection of a Teacher And a Man who must Meet a Cat in The First Manned Space Station"                                | 2006 | "Family"      | "Russell Close, Goldie Brody, Ellen Presley"                                                                                                                                                         |
      | "Bill Others"                 | "A Stunning Saga of a Mad Scientist And a Forensic Psychologist who must Challenge a Squirrel in A MySQL Convention"                 | 2006 | "Documentary" | "Dustin Tautou, Russell Temple, Chris Bridges, Al Garland, Minnie Zellweger, Laurence Bullock"                                                                                                       |
      | "Bingo Talented"              | "A Touching Tale of a Girl And a Crocodile who must Discover a Waitress in Nigeria"                                                  | 2006 | "Sci-Fi"      | "Goldie Brody, Cameron Wray, Cary Mcconaughey, Renee Ball, Jon Chase"                                                                                                                                |
      | "Birch Antitrust"             | "A Fanciful Panorama of a Husband And a Pioneer who must Outgun a Dog in A Baloon"                                                   | 2006 | "Music"       | "Daryl Wahlberg, Matthew Carrey, Alan Dreyfuss, Joe Swank, Ewan Gooding, Woody Hoffman"                                                                                                              |
      | "Bird Independence"           | "A Thrilling Documentary of a Car And a Student who must Sink a Hunter in The Canadian Rockies"                                      | 2006 | "Travel"      | "Fay Kilmer, Jayne Nolte"                                                                                                                                                                            |
      | "Birdcage Casper"             | "A Fast-Paced Saga of a Frisbee And a Astronaut who must Overcome a Feminist in Ancient India"                                       | 2006 | "Music"       | "Kenneth Pesci, Kenneth Torn, Salma Nolte, Renee Ball"                                                                                                                                               |
      | "Birds Perdition"             | "A Boring Story of a Womanizer And a Pioneer who must Face a Dog in California"                                                      | 2006 | "New"         | "Sandra Peck, Gary Penn, Whoopi Hurt, Sylvester Dern"                                                                                                                                                |
      | "Blackout Private"            | "A Intrepid Yarn of a Pastry Chef And a Mad Scientist who must Challenge a Secret Agent in Ancient Japan"                            | 2006 | "Animation"   | "Matthew Carrey, Cameron Zellweger, Cary Mcconaughey, Sandra Kilmer, Kenneth Hoffman"                                                                                                                |
      | "Blade Polish"                | "A Thoughtful Character Study of a Frisbee And a Pastry Chef who must Fight a Dentist in The First Manned Space Station"             | 2006 | "Drama"       | "Kevin Garland, River Dean, Jennifer Davis, Angela Witherspoon, Alec Wayne"                                                                                                                          |
      | "Blanket Beverly"             | "A Emotional Documentary of a Student And a Girl who must Build a Boat in Nigeria"                                                   | 2006 | "Family"      | "Alan Dreyfuss, Thora Temple, Fred Costner, Burt Temple"                                                                                                                                             |
      | "Blindness Gun"               | "A Touching Drama of a Robot And a Dentist who must Meet a Hunter in A Jet Boat"                                                     | 2006 | "Sci-Fi"      | "Burt Dukakis, Chris Bridges, Adam Hopper"                                                                                                                                                           |
      | "Blood Argonauts"             | "A Boring Drama of a Explorer And a Man who must Kill a Lumberjack in A Manhattan Penthouse"                                         | 2006 | "Family"      | "Adam Hopper, Cate Mcqueen, Laura Brody, Cuba Birch"                                                                                                                                                 |
      | "Blues Instinct"              | "A Insightful Documentary of a Boat And a Composer who must Meet a Forensic Psychologist in An Abandoned Fun House"                  | 2006 | "Family"      | "Salma Nolte, Groucho Dunst, Cameron Streep, Matthew Carrey"                                                                                                                                         |
      | "Boiled Dares"                | "A Awe-Inspiring Story of a Waitress And a Dog who must Discover a Dentist in Ancient Japan"                                         | 2006 | "Travel"      | "Julia Fawcett, Tim Hackman, Morgan Hopkins, Gregory Gooding, Dan Torn, Jim Mostel, Nick Stallone, Penelope Pinkett"                                                                                 |
      | "Bonnie Holocaust"            | "A Fast-Paced Story of a Crocodile And a Robot who must Find a Moose in Ancient Japan"                                               | 2006 | "Documentary" | "Susan Davis, Fay Winslet, Oprah Kilmer, Johnny Lollobrigida, Frances Tomei, Minnie Zellweger, Julia Mcqueen, Ed Guiness, Henry Berry"                                                               |
      | "Boogie Amelie"               | "A Lacklusture Character Study of a Husband And a Sumo Wrestler who must Succumb a Technical Writer in The Gulf of Mexico"           | 2006 | "Music"       | "Gene Mckellen, Nick Degeneres, Jodie Degeneres, Meryl Allen, Groucho Sinatra, Kevin Bloom"                                                                                                          |
      | "Boondock Ballroom"           | "A Fateful Panorama of a Crocodile And a Boy who must Defeat a Monkey in The Gulf of Mexico"                                         | 2006 | "Travel"      | "Jennifer Davis, Humphrey Garland, Audrey Bailey, Warren Jackman, Sandra Peck, Chris Bridges, Ed Chase, Ray Johansson, Kenneth Pesci, Dan Harris, Kirsten Paltrow, Fred Costner, Uma Wood"           |
      | "Born Spinal"                 | "A Touching Epistle of a Frisbee And a Husband who must Pursue a Student in Nigeria"                                                 | 2006 | "Travel"      | "Dan Streep, Nick Stallone, Meryl Allen, Kenneth Paltrow, Rita Reynolds, Ray Johansson, Kirsten Paltrow, Sissy Sobieski, Dustin Tautou"                                                              |
      | "Borrowers Bedazzled"         | "A Brilliant Epistle of a Teacher And a Sumo Wrestler who must Defeat a Man in An Abandoned Fun House"                               | 2006 | "Animation"   | "Elvis Marx, Kirk Jovovich, Cuba Olivier, Jon Chase, Daryl Crawford, Harvey Hope, Scarlett Damon"                                                                                                    |
      | "Boulevard Mob"               | "A Fateful Epistle of a Moose And a Monkey who must Confront a Lumberjack in Ancient China"                                          | 2006 | "New"         | "Morgan Mcdormand, Ewan Gooding, Audrey Olivier, Rip Crawford, Kirsten Akroyd, Dan Streep, Angela Witherspoon, Harvey Hope"                                                                          |
      | "Bound Cheaper"               | "A Thrilling Panorama of a Database Administrator And a Astronaut who must Challenge a Lumberjack in A Baloon"                       | 2006 | "Classics"    | "Cuba Olivier, Karl Berry"                                                                                                                                                                           |
      | "Bowfinger Gables"            | "A Fast-Paced Yarn of a Waitress And a Composer who must Outgun a Dentist in California"                                             | 2006 | "Horror"      | "Minnie Zellweger, Michelle Mcconaughey, Will Wilson, Carmen Hunt, Karl Berry"                                                                                                                       |
      | "Brannigan Sunrise"           | "A Amazing Epistle of a Moose And a Crocodile who must Outrace a Dog in Berlin"                                                      | 2006 | "New"         | "Kenneth Hoffman, Rip Crawford"                                                                                                                                                                      |
      | "Braveheart Human"            | "A Insightful Story of a Dog And a Pastry Chef who must Battle a Girl in Berlin"                                                     | 2006 | "Family"      | "Kirsten Akroyd, Jayne Nolte, Nick Stallone, Jane Jackman"                                                                                                                                           |
      | "Breakfast Goldfinger"        | "A Beautiful Reflection of a Student And a Student who must Fight a Moose in Berlin"                                                 | 2006 | "New"         | "Michael Bolger, Russell Temple, Julia Zellweger, Angelina Astaire, Al Garland"                                                                                                                      |
      | "Breaking Home"               | "A Beautiful Display of a Secret Agent And a Monkey who must Battle a Sumo Wrestler in An Abandoned Mine Shaft"                      | 2006 | "New"         | "Helen Voight, Woody Hoffman, Carmen Hunt, Frances Tomei, Morgan Williams, Grace Mostel"                                                                                                             |
      | "Bride Intrigue"              | "A Epic Tale of a Robot And a Monkey who must Vanquish a Man in New Orleans"                                                         | 2006 | "Action"      | "Angela Hudson"                                                                                                                                                                                      |
      | "Bright Encounters"           | "A Fateful Yarn of a Lumberjack And a Feminist who must Conquer a Student in A Jet Boat"                                             | 2006 | "Drama"       | "Albert Nolte, Renee Ball, Cameron Zellweger, Meryl Allen"                                                                                                                                           |
      | "Bringing Hysterical"         | "A Fateful Saga of a A Shark And a Technical Writer who must Find a Woman in A Jet Boat"                                             | 2006 | "Comedy"      | "Frances Day-Lewis, Angela Witherspoon"                                                                                                                                                              |
      | "Brooklyn Desert"             | "A Beautiful Drama of a Dentist And a Composer who must Battle a Sumo Wrestler in The First Manned Space Station"                    | 2006 | "Foreign"     | "Groucho Williams, Albert Nolte, Jodie Degeneres, Jayne Neeson, Sean Guiness"                                                                                                                        |
      | "Brotherhood Blanket"         | "A Fateful Character Study of a Butler And a Technical Writer who must Sink a Astronaut in Ancient Japan"                            | 2006 | "Documentary" | "Jude Cruise, Jayne Neeson, Daryl Crawford, Fred Costner, Frances Day-Lewis"                                                                                                                         |
      | "Bubble Grosse"               | "A Awe-Inspiring Panorama of a Crocodile And a Moose who must Confront a Girl in A Baloon"                                           | 2006 | "Sports"      | "Mena Hopper, Rock Dukakis, Vivien Basinger"                                                                                                                                                         |
      | "Bucket Brotherhood"          | "A Amazing Display of a Girl And a Womanizer who must Succumb a Lumberjack in A Baloon Factory"                                      | 2006 | "Travel"      | "Rip Crawford, Burt Temple, Gary Phoenix, Charlize Dench, Kirsten Akroyd, Tim Hackman"                                                                                                               |
      | "Bugsy Song"                  | "A Awe-Inspiring Character Study of a Secret Agent And a Boat who must Find a Squirrel in The First Manned Space Station"            | 2006 | "Foreign"     | "Kirsten Akroyd, Woody Jolie"                                                                                                                                                                        |
      | "Bull Shawshank"              | "A Fanciful Drama of a Moose And a Squirrel who must Conquer a Pioneer in The Canadian Rockies"                                      | 2006 | "Action"      | "Kirk Jovovich, Alec Wayne, Dan Streep, Julianne Dench, Jayne Nolte, Sandra Kilmer, Angela Witherspoon, Nick Wahlberg"                                                                               |
      | "Bulworth Commandments"       | "A Amazing Display of a Mad Cow And a Pioneer who must Redeem a Sumo Wrestler in The Outback"                                        | 2006 | "Games"       | "Penelope Guiness, Alan Dreyfuss, Scarlett Bening, Angela Hudson"                                                                                                                                    |
      | "Bunch Minds"                 | "A Emotional Story of a Feminist And a Feminist who must Escape a Pastry Chef in A MySQL Convention"                                 | 2006 | "Drama"       | "Ewan Gooding, Woody Hoffman, Laurence Bullock, Karl Berry, Johnny Cage, Chris Bridges, Jada Ryder, Greta Keitel"                                                                                    |
      | "Butch Panther"               | "A Lacklusture Yarn of a Feminist And a Database Administrator who must Face a Hunter in New Orleans"                                | 2006 | "New"         | "Carmen Hunt, Cuba Olivier, Groucho Dunst"                                                                                                                                                           |
      | "Butterfly Chocolat"          | "A Fateful Story of a Girl And a Composer who must Conquer a Husband in A Shark Tank"                                                | 2006 | "New"         | "Mena Temple, Kim Allen, Ed Guiness, Lisa Monroe, Burt Temple, Mary Keitel, Nick Stallone"                                                                                                           |
      | "Cabin Flash"                 | "A Stunning Epistle of a Boat And a Man who must Challenge a A Shark in A Baloon Factory"                                            | 2006 | "Children"    | "Ben Willis, Uma Wood, Renee Ball, Alec Wayne"                                                                                                                                                       |
      | "Caddyshack Jedi"             | "A Awe-Inspiring Epistle of a Woman And a Madman who must Fight a Robot in Soviet Georgia"                                           | 2006 | "Action"      | "Meryl Gibson, Natalie Hopkins, Rock Dukakis, Tom Mckellen, Elvis Marx, Kenneth Paltrow, Ed Chase"                                                                                                   |
      | "Calendar Gunfight"           | "A Thrilling Drama of a Frisbee And a Lumberjack who must Sink a Man in Nigeria"                                                     | 2006 | "Foreign"     | "Tim Hackman, Greta Keitel, Milla Peck, Gary Phoenix, Cameron Streep, Bette Nicholson, Gina Degeneres, Whoopi Hurt"                                                                                  |
      | "California Birds"            | "A Thrilling Yarn of a Database Administrator And a Robot who must Battle a Database Administrator in Ancient India"                 | 2006 | "Sports"      | "Scarlett Bening, Russell Close"                                                                                                                                                                     |
      | "Camelot Vacation"            | "A Touching Character Study of a Woman And a Waitress who must Battle a Pastry Chef in A MySQL Convention"                           | 2006 | "Sci-Fi"      | "Jude Cruise, Albert Nolte"                                                                                                                                                                          |
      | "Campus Remember"             | "A Astounding Drama of a Crocodile And a Mad Cow who must Build a Robot in A Jet Boat"                                               | 2006 | "Action"      | "Reese Kilmer, Matthew Johansson, Will Wilson"                                                                                                                                                       |
      | "Candidate Perdition"         | "A Brilliant Epistle of a Composer And a Database Administrator who must Vanquish a Mad Scientist in The First Manned Space Station" | 2006 | "Classics"    | "Morgan Hopkins, Sandra Kilmer, Thora Temple, Sidney Crowe"                                                                                                                                          |
      | "Candles Grapes"              | "A Fanciful Character Study of a Monkey And a Explorer who must Build a Astronaut in An Abandoned Fun House"                         | 2006 | "Games"       | "Reese Kilmer, Albert Johansson, Milla Keitel, Angela Hudson, Charlize Dench, John Suvari, Sandra Kilmer"                                                                                            |
      | "Canyon Stock"                | "A Thoughtful Reflection of a Waitress And a Feminist who must Escape a Squirrel in A Manhattan Penthouse"                           | 2006 | "Animation"   | "Russell Temple, Matthew Leigh, Spencer Depp, Ralph Cruz, Zero Cage, Val Bolger"                                                                                                                     |
      | "Caper Motions"               | "A Fateful Saga of a Moose And a Car who must Pursue a Woman in A MySQL Convention"                                                  | 2006 | "Comedy"      | "Cate Mcqueen, Helen Voight, Audrey Olivier, Christian Akroyd, Val Bolger, Burt Temple, Kevin Garland"                                                                                               |
      | "Caribbean Liberty"           | "A Fanciful Tale of a Pioneer And a Technical Writer who must Outgun a Pioneer in A Shark Tank"                                      | 2006 | "Sports"      | "Ellen Presley, Laurence Bullock, Chris Bridges, Kim Allen, Ben Willis, Jane Jackman, Harvey Hope, Susan Davis"                                                                                      |
      | "Carol Texas"                 | "A Astounding Character Study of a Composer And a Student who must Overcome a Composer in A Monastery"                               | 2006 | "Animation"   | "Ben Willis, Oprah Kilmer, Thora Temple, Vivien Basinger, Dustin Tautou, Fred Costner, Gary Phoenix"                                                                                                 |
      | "Carrie Bunch"                | "A Amazing Epistle of a Student And a Astronaut who must Discover a Frisbee in The Canadian Rockies"                                 | 2006 | "Horror"      | "Bela Walken, Jude Cruise, Greta Malden, Angelina Astaire, Val Bolger, Mena Temple, Kenneth Torn"                                                                                                    |
      | "Casablanca Super"            | "A Amazing Panorama of a Crocodile And a Forensic Psychologist who must Pursue a Secret Agent in The First Manned Space Station"     | 2006 | "Travel"      | "Kirsten Akroyd, Reese West, Walter Torn, Angela Witherspoon"                                                                                                                                        |
      | "Casper Dragonfly"            | "A Intrepid Documentary of a Boat And a Crocodile who must Chase a Robot in The Sahara Desert"                                       | 2006 | "Children"    | "Ray Johansson, Ellen Presley, Walter Torn, Helen Voight, Ralph Cruz"                                                                                                                                |
      | "Cassidy Wyoming"             | "A Intrepid Drama of a Frisbee And a Hunter who must Kill a Secret Agent in New Orleans"                                             | 2006 | "Travel"      | "Mary Keitel, Cuba Olivier, Sandra Kilmer, Lucille Dee, Audrey Olivier, Angela Witherspoon, Angela Hudson"                                                                                           |
      | "Casualties Encino"           | "A Insightful Yarn of a A Shark And a Pastry Chef who must Face a Boy in A Monastery"                                                | 2006 | "Action"      | "Mena Temple, Cameron Streep, Daryl Wahlberg, Groucho Dunst, Susan Davis"                                                                                                                            |
      | "Cat Coneheads"               | "A Fast-Paced Panorama of a Girl And a A Shark who must Confront a Boy in Ancient India"                                             | 2006 | "Comedy"      | "Angela Witherspoon, Renee Ball, Laura Brody, Helen Voight"                                                                                                                                          |
      | "Catch Amistad"               | "A Boring Reflection of a Lumberjack And a Feminist who must Discover a Woman in Nigeria"                                            | 2006 | "Foreign"     | "Johnny Cage, Ian Tandy, Christian Akroyd, Dan Streep, Kenneth Pesci"                                                                                                                                |
      | "Cause Date"                  | "A Taut Tale of a Explorer And a Pastry Chef who must Conquer a Hunter in A MySQL Convention"                                        | 2006 | "Documentary" | "William Hackman, Penelope Pinkett, Jayne Neeson, Reese West, Dustin Tautou, Jayne Silverstone"                                                                                                      |
      | "Celebrity Horn"              | "A Amazing Documentary of a Secret Agent And a Astronaut who must Vanquish a Hunter in A Shark Tank"                                 | 2006 | "Action"      | "Dustin Tautou, Matthew Leigh, Jayne Silverstone, Angela Witherspoon"                                                                                                                                |
      | "Center Dinosaur"             | "A Beautiful Character Study of a Sumo Wrestler And a Dentist who must Find a Dog in California"                                     | 2006 | "Classics"    | "Ed Guiness, Alec Wayne, Geoffrey Heston, Fay Winslet"                                                                                                                                               |
      | "Chainsaw Uptown"             | "A Beautiful Documentary of a Boy And a Robot who must Discover a Squirrel in Australia"                                             | 2006 | "Sci-Fi"      | "Gene Hopkins, Nick Wahlberg"                                                                                                                                                                        |
      | "Chamber Italian"             | "A Fateful Reflection of a Moose And a Husband who must Overcome a Monkey in Nigeria"                                                | 2006 | "Music"       | "Richard Penn, Adam Hopper, Rip Winslet, Emily Dee, Henry Berry, Alec Wayne, Gina Degeneres"                                                                                                         |
      | "Champion Flatliners"         | "A Amazing Story of a Mad Cow And a Dog who must Kill a Husband in A Monastery"                                                      | 2006 | "Animation"   | "Jude Cruise, Gene Willis, Cameron Wray, Frances Day-Lewis"                                                                                                                                          |
      | "Chance Resurrection"         | "A Astounding Story of a Forensic Psychologist And a Forensic Psychologist who must Overcome a Moose in Ancient China"               | 2006 | "Sports"      | "Meryl Allen, Angela Witherspoon, Milla Peck, Ben Willis, Whoopi Hurt, Christian Akroyd"                                                                                                             |
      | "Chaplin License"             | "A Boring Drama of a Dog And a Forensic Psychologist who must Outrace a Explorer in Ancient India"                                   | 2006 | "New"         | "Gina Degeneres, Minnie Kilmer, Tim Hackman, Penelope Cronyn, Cuba Allen, Groucho Dunst"                                                                                                             |
      | "Charade Duffel"              | "A Action-Packed Display of a Man And a Waitress who must Build a Dog in A MySQL Convention"                                         | 2006 | "Sci-Fi"      | "Kirsten Akroyd, Greg Chaplin, Warren Nolte"                                                                                                                                                         |
      | "Chariots Conspiracy"         | "A Unbelieveable Epistle of a Robot And a Husband who must Chase a Robot in The First Manned Space Station"                          | 2006 | "Sci-Fi"      | "Gina Degeneres, Michael Bolger"                                                                                                                                                                     |
      | "Chasing Fight"               | "A Astounding Saga of a Technical Writer And a Butler who must Battle a Butler in A Shark Tank"                                      | 2006 | "Family"      | "Jada Ryder, Fay Winslet, Russell Temple, Mena Hopper, Tom Miranda"                                                                                                                                  |
      | "Cheaper Clyde"               | "A Emotional Character Study of a Pioneer And a Girl who must Discover a Dog in Ancient Japan"                                       | 2006 | "Sci-Fi"      | "Lucille Tracy, Penelope Guiness"                                                                                                                                                                    |
      | "Chicago North"               | "A Fateful Yarn of a Mad Cow And a Waitress who must Battle a Student in California"                                                 | 2006 | "Games"       | "River Dean, Burt Temple, Jayne Silverstone, Liza Bergman, Mae Hoffman, Meryl Gibson, Kevin Garland, Cuba Allen"                                                                                     |
      | "Chicken Hellfighters"        | "A Emotional Drama of a Dog And a Explorer who must Outrace a Technical Writer in Australia"                                         | 2006 | "Documentary" | "Henry Berry, Kirsten Paltrow"                                                                                                                                                                       |
      | "Chill Luck"                  | "A Lacklusture Epistle of a Boat And a Technical Writer who must Fight a A Shark in The Canadian Rockies"                            | 2006 | "Drama"       | "Meg Hawke, Woody Jolie, Warren Jackman, Mary Tandy, Burt Posey"                                                                                                                                     |
      | "Chinatown Gladiator"         | "A Brilliant Panorama of a Technical Writer And a Lumberjack who must Escape a Butler in Ancient India"                              | 2006 | "New"         | "Uma Wood, Bob Fawcett, Jayne Silverstone, Jeff Silverstone, Dan Torn, Jessica Bailey, Penelope Monroe, Jude Cruise, Sean Williams, Geoffrey Heston"                                                 |
      | "Chisum Behavior"             | "A Epic Documentary of a Sumo Wrestler And a Butler who must Kill a Car in Ancient India"                                            | 2006 | "Family"      | "Fay Winslet, Julia Fawcett, Gene Hopkins, Nick Wahlberg"                                                                                                                                            |
      | "Chitty Lock"                 | "A Boring Epistle of a Boat And a Database Administrator who must Kill a Sumo Wrestler in The First Manned Space Station"            | 2006 | "Drama"       | "Olympia Pfeiffer, Al Garland, Susan Davis, Lisa Monroe, Lucille Tracy, Johnny Lollobrigida, Humphrey Garland, Nick Degeneres, Elvis Marx, Rock Dukakis, Val Bolger, Sissy Sobieski, Russell Temple" |
      | "Chocolat Harry"              | "A Action-Packed Epistle of a Dentist And a Moose who must Meet a Mad Cow in Ancient Japan"                                          | 2006 | "Family"      | "Jane Jackman, Joe Swank, Rip Crawford, Kirk Jovovich, Reese West"                                                                                                                                   |
      | "Chocolate Duck"              | "A Unbelieveable Story of a Mad Scientist And a Technical Writer who must Discover a Composer in Ancient China"                      | 2006 | "Foreign"     | "Humphrey Willis, Cameron Streep, Joe Swank, Julianne Dench, Minnie Zellweger, Groucho Williams, Gary Penn"                                                                                          |
      | "Christmas Moonshine"         | "A Action-Packed Epistle of a Feminist And a Astronaut who must Conquer a Boat in A Manhattan Penthouse"                             | 2006 | "Children"    | "Penelope Monroe, Emily Dee, Thora Temple"                                                                                                                                                           |
      | "Cider Desire"                | "A Stunning Character Study of a Composer And a Mad Cow who must Succumb a Cat in Soviet Georgia"                                    | 2006 | "Documentary" | "Julia Mcqueen, Penelope Pinkett, Jodie Degeneres, Frances Day-Lewis, Jon Chase"                                                                                                                     |
      | "Cincinatti Whisperer"        | "A Brilliant Saga of a Pastry Chef And a Hunter who must Confront a Butler in Berlin"                                                | 2006 | "Sci-Fi"      | "Anne Cronyn, Russell Bacall, Cuba Allen, Julianne Dench"                                                                                                                                            |
      | "Circus Youth"                | "A Thoughtful Drama of a Pastry Chef And a Dentist who must Pursue a Girl in A Baloon"                                               | 2006 | "Children"    | "Matthew Carrey, Bob Fawcett"                                                                                                                                                                        |
      | "Citizen Shrek"               | "A Fanciful Character Study of a Technical Writer And a Husband who must Redeem a Robot in The Outback"                              | 2006 | "Sci-Fi"      | "Russell Temple, Jude Cruise, Kevin Bloom, Cary Mcconaughey, Ben Harris, Gary Phoenix, Kenneth Torn, Ian Tandy"                                                                                      |
      | "Clash Freddy"                | "A Amazing Yarn of a Composer And a Squirrel who must Escape a Astronaut in Australia"                                               | 2006 | "Animation"   | "Vivien Bergen, Uma Wood, Helen Voight, Kim Allen, Alan Dreyfuss, Liza Bergman, Milla Peck"                                                                                                          |
      | "Cleopatra Devil"             | "A Fanciful Documentary of a Crocodile And a Technical Writer who must Fight a A Shark in A Baloon"                                  | 2006 | "New"         | "Ewan Gooding, Karl Berry, Fred Costner, John Suvari, William Hackman, Fay Wood, Kim Allen"                                                                                                          |
      | "Clerks Angels"               | "A Thrilling Display of a Sumo Wrestler And a Girl who must Confront a Man in A Baloon"                                              | 2006 | "Documentary" | "Adam Hopper, Susan Davis, Bela Walken, Penelope Cronyn"                                                                                                                                             |
      | "Clockwork Paradise"          | "A Insightful Documentary of a Technical Writer And a Feminist who must Challenge a Cat in A Baloon"                                 | 2006 | "Children"    | "Kevin Garland, Sylvester Dern, Salma Nolte, Lucille Dee, Spencer Peck"                                                                                                                              |
      | "Clones Pinocchio"            | "A Amazing Drama of a Car And a Robot who must Pursue a Dentist in New Orleans"                                                      | 2006 | "Music"       | "Sidney Crowe, Matthew Johansson, Angela Hudson, Salma Nolte, Meryl Gibson"                                                                                                                          |
      | "Closer Bang"                 | "A Unbelieveable Panorama of a Frisbee And a Hunter who must Vanquish a Monkey in Ancient India"                                     | 2006 | "Comedy"      | "Kirsten Paltrow, Greta Malden, Ed Guiness, Jodie Degeneres, Russell Temple, Julia Fawcett"                                                                                                          |
      | "Club Graffiti"               | "A Epic Tale of a Pioneer And a Hunter who must Escape a Girl in A U-Boat"                                                           | 2006 | "Animation"   | "Tom Mckellen, Debbie Akroyd, Morgan Williams, Lisa Monroe"                                                                                                                                          |
      | "Clue Grail"                  | "A Taut Tale of a Butler And a Mad Scientist who must Build a Crocodile in Ancient China"                                            | 2006 | "Music"       | "Kirk Jovovich, Rip Winslet, Gene Hopkins, Liza Bergman, Meryl Allen, Spencer Peck"                                                                                                                  |
      | "Clueless Bucket"             | "A Taut Tale of a Car And a Pioneer who must Conquer a Sumo Wrestler in An Abandoned Fun House"                                      | 2006 | "Action"      | "Charlize Dench, Alan Dreyfuss, Jon Chase, Gina Degeneres, Morgan Mcdormand, Adam Hopper, Cameron Zellweger, Uma Wood"                                                                               |
      | "Clyde Theory"                | "A Beautiful Yarn of a Astronaut And a Frisbee who must Overcome a Explorer in A Jet Boat"                                           | 2006 | "New"         | "Greg Chaplin, Meryl Allen, Johnny Cage, Sissy Sobieski"                                                                                                                                             |
      | "Coast Rainbow"               | "A Astounding Documentary of a Mad Cow And a Pioneer who must Challenge a Butler in The Sahara Desert"                               | 2006 | "Documentary" | "Sissy Sobieski, Angela Witherspoon, Lisa Monroe, Bette Nicholson, Reese West, Frances Day-Lewis, Oprah Kilmer, Cameron Streep, Reese Kilmer, Burt Temple"                                           |
      | "Coldblooded Darling"         | "A Brilliant Panorama of a Dentist And a Moose who must Find a Student in The Gulf of Mexico"                                        | 2006 | "Sci-Fi"      | "Bette Nicholson, Lucille Tracy, Gina Degeneres, Ben Willis"                                                                                                                                         |
      | "Color Philadelphia"          | "A Thoughtful Panorama of a Car And a Crocodile who must Sink a Monkey in The Sahara Desert"                                         | 2006 | "Classics"    | "Daryl Crawford, Salma Nolte, Christopher West, Olympia Pfeiffer, Penelope Guiness, Groucho Dunst, John Suvari"                                                                                      |
      | "Coma Head"                   | "A Awe-Inspiring Drama of a Boy And a Frisbee who must Escape a Pastry Chef in California"                                           | 2006 | "Travel"      | "Geoffrey Heston, Cameron Wray, Renee Tracy"                                                                                                                                                         |
      | "Comancheros Enemy"           | "A Boring Saga of a Lumberjack And a Monkey who must Find a Monkey in The Gulf of Mexico"                                            | 2006 | "Children"    | "Cate Mcqueen, Jayne Nolte, Michael Bening, Goldie Brody, Renee Ball"                                                                                                                                |
      | "Comforts Rush"               | "A Unbelieveable Panorama of a Pioneer And a Husband who must Meet a Mad Cow in An Abandoned Mine Shaft"                             | 2006 | "Travel"      | "Russell Temple, Bela Walken, Humphrey Willis, Humphrey Garland, Meryl Gibson"                                                                                                                       |
      | "Command Darling"             | "A Awe-Inspiring Tale of a Forensic Psychologist And a Woman who must Challenge a Database Administrator in Ancient Japan"           | 2006 | "Foreign"     | "Rita Reynolds, Ewan Gooding, Meryl Gibson, Kenneth Pesci, Liza Bergman, Geoffrey Heston, Grace Mostel, Burt Posey"                                                                                  |
      | "Commandments Express"        | "A Fanciful Saga of a Student And a Mad Scientist who must Battle a Hunter in An Abandoned Mine Shaft"                               | 2006 | "Horror"      | "Cuba Birch, Burt Dukakis, Warren Jackman, Johnny Lollobrigida"                                                                                                                                      |
      | "Coneheads Smoochy"           | "A Touching Story of a Womanizer And a Composer who must Pursue a Husband in Nigeria"                                                | 2006 | "Drama"       | "Warren Jackman, Alec Wayne, Richard Penn, Gina Degeneres, Julia Barrymore, Johnny Lollobrigida, Dan Torn, Julia Mcqueen, Audrey Olivier"                                                            |
      | "Confessions Maguire"         | "A Insightful Story of a Car And a Boy who must Battle a Technical Writer in A Baloon"                                               | 2006 | "Drama"       | "Russell Bacall, Grace Mostel, Warren Jackman, Audrey Bailey"                                                                                                                                        |
      | "Confidential Interview"      | "A Stunning Reflection of a Cat And a Woman who must Find a Astronaut in Ancient Japan"                                              | 2006 | "Music"       | "Parker Goldberg, Sylvester Dern"                                                                                                                                                                    |
      | "Confused Candles"            | "A Stunning Epistle of a Cat And a Forensic Psychologist who must Confront a Pioneer in A Baloon"                                    | 2006 | "Family"      | "Ralph Cruz, Christian Akroyd, River Dean, Albert Nolte, Gene Mckellen, James Pitt"                                                                                                                  |
      | "Congeniality Quest"          | "A Touching Documentary of a Cat And a Pastry Chef who must Find a Lumberjack in A Baloon"                                           | 2006 | "Sports"      | "Christopher Berry, Nick Stallone, Tom Mckellen"                                                                                                                                                     |
      | "Connecticut Tramp"           | "A Unbelieveable Drama of a Crocodile And a Mad Cow who must Reach a Dentist in A Shark Tank"                                        | 2006 | "Sci-Fi"      | "Vivien Basinger, Albert Johansson, Meg Hawke, Henry Berry, Fred Costner, Karl Berry, Johnny Cage"                                                                                                   |
      | "Connection Microcosmos"      | "A Fateful Documentary of a Crocodile And a Husband who must Face a Husband in The First Manned Space Station"                       | 2006 | "Comedy"      | "Natalie Hopkins, Renee Tracy, Russell Temple, Cameron Streep, Vivien Basinger, Scarlett Damon, Fay Winslet"                                                                                         |
      | "Conquerer Nuts"              | "A Taut Drama of a Mad Scientist And a Man who must Escape a Pioneer in An Abandoned Mine Shaft"                                     | 2006 | "Drama"       | "Matthew Johansson, Henry Berry, Kevin Bloom, John Suvari, Cameron Zellweger, Kirsten Paltrow"                                                                                                       |
      | "Conspiracy Spirit"           | "A Awe-Inspiring Story of a Student And a Frisbee who must Conquer a Crocodile in An Abandoned Mine Shaft"                           | 2006 | "Classics"    | "Kirk Jovovich, Minnie Kilmer, Mena Hopper, Christopher West"                                                                                                                                        |
      | "Contact Anonymous"           | "A Insightful Display of a A Shark And a Monkey who must Face a Database Administrator in Ancient India"                             | 2006 | "Travel"      | "Mena Temple, Olympia Pfeiffer, Ewan Gooding, Christopher Berry, Morgan Hopkins"                                                                                                                     |
      | "Control Anthem"              | "A Fateful Documentary of a Robot And a Student who must Battle a Cat in A Monastery"                                                | 2006 | "Comedy"      | "Charlize Dench, Bob Fawcett, Audrey Olivier"                                                                                                                                                        |
      | "Conversation Downhill"       | "A Taut Character Study of a Husband And a Waitress who must Sink a Squirrel in A MySQL Convention"                                  | 2006 | "Family"      | "Greta Malden, Chris Bridges, Dustin Tautou"                                                                                                                                                         |
      | "Core Suit"                   | "A Unbelieveable Tale of a Car And a Explorer who must Confront a Boat in A Manhattan Penthouse"                                     | 2006 | "Classics"    | "Penelope Pinkett, Penelope Cronyn, Mena Hopper, Angela Witherspoon"                                                                                                                                 |
      | "Cowboy Doom"                 | "A Astounding Drama of a Boy And a Lumberjack who must Fight a Butler in A Baloon"                                                   | 2006 | "Foreign"     | "Milla Keitel, Whoopi Hurt, Ed Chase, Julianne Dench, Gregory Gooding"                                                                                                                               |
      | "Craft Outfield"              | "A Lacklusture Display of a Explorer And a Hunter who must Succumb a Database Administrator in A Baloon Factory"                     | 2006 | "Drama"       | "Jada Ryder, Henry Berry, Scarlett Damon, Liza Bergman, Mary Keitel, Rip Crawford"                                                                                                                   |
      | "Cranes Reservoir"            | "A Fanciful Documentary of a Teacher And a Dog who must Outgun a Forensic Psychologist in A Baloon Factory"                          | 2006 | "Sports"      | "Reese Kilmer, Charlize Dench, Vivien Bergen, Angelina Astaire, Laura Brody, Julia Zellweger"                                                                                                        |
      | "Crazy Home"                  | "A Fanciful Panorama of a Boy And a Woman who must Vanquish a Database Administrator in The Outback"                                 | 2006 | "Comedy"      | "Harvey Hope, Albert Nolte, Meg Hawke, Woody Jolie, Gene Mckellen, Russell Bacall, Sissy Sobieski, Alan Dreyfuss, Morgan Mcdormand, Cate Harris, Russell Temple, Will Wilson, Vivien Basinger"       |
      | "Creatures Shakespeare"       | "A Emotional Drama of a Womanizer And a Squirrel who must Vanquish a Crocodile in Ancient India"                                     | 2006 | "Games"       | "Groucho Dunst, Reese West, Susan Davis"                                                                                                                                                             |
      | "Creepers Kane"               | "A Awe-Inspiring Reflection of a Squirrel And a Boat who must Outrace a Car in A Jet Boat"                                           | 2006 | "Classics"    | "William Hackman, Jayne Nolte, Sylvester Dern, Renee Tracy, Scarlett Bening, Christopher Berry"                                                                                                      |
      | "Crooked Frogmen"             | "A Unbelieveable Drama of a Hunter And a Database Administrator who must Battle a Crocodile in An Abandoned Amusement Park"          | 2006 | "Children"    | "Cate Harris, Christian Gable, Albert Johansson, Joe Swank, William Hackman, Laurence Bullock"                                                                                                       |
      | "Crossing Divorce"            | "A Beautiful Documentary of a Dog And a Robot who must Redeem a Womanizer in Berlin"                                                 | 2006 | "Foreign"     | "Milla Keitel, Jude Cruise"                                                                                                                                                                          |
      | "Crossroads Casualties"       | "A Intrepid Documentary of a Sumo Wrestler And a Astronaut who must Battle a Composer in The Outback"                                | 2006 | "Animation"   | "Ed Guiness, Frances Tomei, Bette Nicholson, Kenneth Torn, Russell Temple, Kenneth Pesci, Ed Mansfield, Meryl Gibson"                                                                                |
      | "Crow Grease"                 | "A Awe-Inspiring Documentary of a Woman And a Husband who must Sink a Database Administrator in The First Manned Space Station"      | 2006 | "Action"      | "Cameron Streep, Frances Tomei, Walter Torn, Scarlett Damon, Chris Bridges, Jodie Degeneres, Lisa Monroe, Cameron Zellweger, Groucho Dunst, Morgan Mcdormand"                                        |
      | "Crowds Telemark"             | "A Intrepid Documentary of a Astronaut And a Forensic Psychologist who must Find a Frisbee in An Abandoned Fun House"                | 2006 | "Sci-Fi"      | "Anne Cronyn, Jeff Silverstone, Matthew Johansson, Matthew Carrey"                                                                                                                                   |
      | "Cruelty Unforgiven"          | "A Brilliant Tale of a Car And a Moose who must Battle a Dentist in Nigeria"                                                         | 2006 | "Classics"    | "Will Wilson, Greg Chaplin"                                                                                                                                                                          |
      | "Crusade Honey"               | "A Fast-Paced Reflection of a Explorer And a Butler who must Battle a Madman in An Abandoned Amusement Park"                         | 2006 | "Sports"      | "Meg Hawke, Albert Johansson, Sean Guiness, Matthew Leigh, Lisa Monroe, Renee Tracy, Ray Johansson, Tim Hackman, Fay Kilmer"                                                                         |
      | "Crystal Breaking"            | "A Fast-Paced Character Study of a Feminist And a Explorer who must Face a Pastry Chef in Ancient Japan"                             | 2006 | "Foreign"     | "Jayne Neeson, Penelope Cronyn, Liza Bergman, Reese Kilmer, Fay Wood"                                                                                                                                |
      | "Cupboard Sinners"            | "A Emotional Reflection of a Frisbee And a Boat who must Reach a Pastry Chef in An Abandoned Amusement Park"                         | 2006 | "Documentary" | "Frances Tomei, Cameron Streep, Tim Hackman, Jada Ryder, Matthew Leigh, Helen Voight, Christian Akroyd, Spencer Peck"                                                                                |
      | "Curtain Videotape"           | "A Boring Reflection of a Dentist And a Mad Cow who must Chase a Secret Agent in A Shark Tank"                                       | 2006 | "Games"       | "Ewan Gooding, Joe Swank, Walter Torn"                                                                                                                                                               |
      | "Cyclone Family"              | "A Lacklusture Drama of a Student And a Monkey who must Sink a Womanizer in A MySQL Convention"                                      | 2006 | "Foreign"     | "Judy Dean, Rip Crawford, Helen Voight"                                                                                                                                                              |
      | "Daddy Pittsburgh"            | "A Epic Story of a A Shark And a Student who must Confront a Explorer in The Gulf of Mexico"                                         | 2006 | "Comedy"      | "Michelle Mcconaughey, Daryl Crawford, Kevin Garland, Kenneth Paltrow, Johnny Lollobrigida"                                                                                                          |
      | "Daisy Menagerie"             | "A Fast-Paced Saga of a Pastry Chef And a Monkey who must Sink a Composer in Ancient India"                                          | 2006 | "Sci-Fi"      | "Johnny Lollobrigida, Uma Wood, Milla Keitel, Minnie Kilmer, Goldie Brody, Jodie Degeneres, Carmen Hunt"                                                                                             |
      | "Dalmations Sweden"           | "A Emotional Epistle of a Moose And a Hunter who must Overcome a Robot in A Manhattan Penthouse"                                     | 2006 | "Drama"       | "Val Bolger, Groucho Dunst, Al Garland, Albert Nolte, Kevin Bloom, Joe Swank"                                                                                                                        |
      | "Dances None"                 | "A Insightful Reflection of a A Shark And a Dog who must Kill a Butler in An Abandoned Amusement Park"                               | 2006 | "Action"      | "Mae Hoffman, Matthew Johansson, Zero Cage, Walter Torn, Rip Winslet"                                                                                                                                |
      | "Dancing Fever"               | "A Stunning Story of a Explorer And a Forensic Psychologist who must Face a Crocodile in A Shark Tank"                               | 2006 | "Documentary" | "Matthew Leigh, Rock Dukakis, Laura Brody, Kenneth Torn, Jane Jackman, Jayne Nolte"                                                                                                                  |
      | "Dangerous Uptown"            | "A Unbelieveable Story of a Mad Scientist And a Woman who must Overcome a Dog in California"                                         | 2006 | "Foreign"     | "Anne Cronyn, Daryl Wahlberg, Albert Johansson, Cate Harris, Spencer Peck, Ralph Cruz, Mary Tandy, Kirsten Akroyd"                                                                                   |
      | "Dares Pluto"                 | "A Fateful Story of a Robot And a Dentist who must Defeat a Astronaut in New Orleans"                                                | 2006 | "Animation"   | "Greta Keitel, Penelope Monroe, Laura Brody, Bob Fawcett, Karl Berry, Meryl Gibson, Cameron Wray, Julia Zellweger, Warren Nolte, Will Wilson"                                                        |
      | "Darkness War"                | "A Touching Documentary of a Husband And a Hunter who must Escape a Boy in The Sahara Desert"                                        | 2006 | "Drama"       | "Gina Degeneres, Gene Willis"                                                                                                                                                                        |
      | "Darko Dorado"                | "A Stunning Reflection of a Frisbee And a Husband who must Redeem a Dog in New Orleans"                                              | 2006 | "Action"      | "Richard Penn, Morgan Mcdormand, Greta Malden, Dustin Tautou"                                                                                                                                        |
      | "Darling Breaking"            | "A Brilliant Documentary of a Astronaut And a Squirrel who must Succumb a Student in The Gulf of Mexico"                             | 2006 | "Games"       | "Jayne Neeson, Frances Day-Lewis"                                                                                                                                                                    |
      | "Darn Forrester"              | "A Fateful Story of a A Shark And a Explorer who must Succumb a Technical Writer in A Jet Boat"                                      | 2006 | "Action"      | "Chris Bridges, Ralph Cruz, Jodie Degeneres, Sandra Kilmer, Charlize Dench, Sean Guiness, Mena Hopper, Cate Mcqueen, Bob Fawcett"                                                                    |
      | "Date Speed"                  | "A Touching Saga of a Composer And a Moose who must Discover a Dentist in A MySQL Convention"                                        | 2006 | "Family"      | "Jude Cruise, Karl Berry, Rip Winslet, Kevin Bloom"                                                                                                                                                  |
      | "Daughter Madigan"            | "A Beautiful Tale of a Hunter And a Mad Scientist who must Confront a Squirrel in The First Manned Space Station"                    | 2006 | "Children"    | "Lucille Dee, Milla Peck, John Suvari, Ed Mansfield"                                                                                                                                                 |
      | "Dawn Pond"                   | "A Thoughtful Documentary of a Dentist And a Forensic Psychologist who must Defeat a Waitress in Berlin"                             | 2006 | "Games"       | "Matthew Leigh, Meryl Allen, Groucho Williams, Rip Winslet, Vivien Basinger, Scarlett Damon"                                                                                                         |
      | "Day Unfaithful"              | "A Stunning Documentary of a Composer And a Mad Scientist who must Find a Technical Writer in A U-Boat"                              | 2006 | "New"         | "Minnie Zellweger, Angela Witherspoon, Greg Chaplin, Julia Fawcett, Karl Berry"                                                                                                                      |
      | "Dazed Punk"                  | "A Action-Packed Story of a Pioneer And a Technical Writer who must Discover a Forensic Psychologist in An Abandoned Amusement Park" | 2006 | "Games"       | "Greta Malden, Ben Willis, Ben Harris, Bob Fawcett, Grace Mostel, Geoffrey Heston"                                                                                                                   |
      | "Deceiver Betrayed"           | "A Taut Story of a Moose And a Squirrel who must Build a Husband in Ancient India"                                                   | 2006 | "Drama"       | "Morgan Hopkins, Grace Mostel, Albert Johansson, Fred Costner"                                                                                                                                       |
      | "Deep Crusade"                | "A Amazing Tale of a Crocodile And a Squirrel who must Discover a Composer in Australia"                                             | 2006 | "Documentary" | "Gregory Gooding, Warren Nolte, Gene Hopkins, Olympia Pfeiffer, Scarlett Damon, Tim Hackman, Reese Kilmer"                                                                                           |
      | "Deer Virginian"              | "A Thoughtful Story of a Mad Cow And a Womanizer who must Overcome a Mad Scientist in Soviet Georgia"                                | 2006 | "Music"       | "Gina Degeneres, Ian Tandy, Liza Bergman"                                                                                                                                                            |
      | "Deliverance Mulholland"      | "A Astounding Saga of a Monkey And a Moose who must Conquer a Butler in A Shark Tank"                                                | 2006 | "Documentary" | "Matthew Leigh, Fred Costner, Humphrey Garland"                                                                                                                                                      |
      | "Desert Poseidon"             | "A Brilliant Documentary of a Butler And a Frisbee who must Build a Astronaut in New Orleans"                                        | 2006 | "Horror"      | "Henry Berry, Goldie Brody, Burt Posey, Renee Ball, Liza Bergman"                                                                                                                                    |
      | "Desire Alien"                | "A Fast-Paced Tale of a Dog And a Forensic Psychologist who must Meet a Astronaut in The First Manned Space Station"                 | 2006 | "Animation"   | "Angelina Astaire, Rock Dukakis, Johnny Cage, Tom Mckellen, Cate Harris, Laura Brody, Julianne Dench"                                                                                                |
      | "Desperate Trainspotting"     | "A Epic Yarn of a Forensic Psychologist And a Teacher who must Face a Lumberjack in California"                                      | 2006 | "Travel"      | "Renee Tracy, Renee Ball, Cary Mcconaughey, Morgan Williams"                                                                                                                                         |
      | "Destination Jerk"            | "A Beautiful Yarn of a Teacher And a Cat who must Build a Car in A U-Boat"                                                           | 2006 | "Drama"       | "Cameron Wray, Grace Mostel, Rip Crawford"                                                                                                                                                           |
      | "Destiny Saturday"            | "A Touching Drama of a Crocodile And a Crocodile who must Conquer a Explorer in Soviet Georgia"                                      | 2006 | "New"         | "Kevin Bloom, Emily Dee, Mary Tandy, Sandra Kilmer, Dan Harris, Alec Wayne, Nick Wahlberg"                                                                                                           |
      | "Details Packer"              | "A Epic Saga of a Waitress And a Composer who must Face a Boat in A U-Boat"                                                          | 2006 | "Games"       | "Michelle Mcconaughey, Salma Nolte"                                                                                                                                                                  |